// packages/map/app/components/users/SignUpForm.tsx
import { MAP, SIGN_IN } from '~/lib/routes'
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { useTranslation } from 'react-i18next'

import { signUpSchema } from '~/common/validation/schemas'
import type { SignUpFormData } from '~/common/validation/schemas'
import { Button } from '~/components/ui/button'
import { ErrorLabel } from '~/components/ui/error-label'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel
} from '~/components/ui/form'
import { Input } from '~/components/ui/input'
import { Link } from '~/components/ui/link'

interface SignUpFormProps {
  onSubmit: (values: SignUpFormData) => void
  signUpSuccess: boolean
  isLoading?: boolean
}

const SignUpForm = ({
  onSubmit,
  signUpSuccess,
  isLoading = false
}: SignUpFormProps) => {
  const { t } = useTranslation()

  const form = useForm<SignUpFormData>({
    resolver: zodResolver(signUpSchema),
    defaultValues: {
      name: '',
      phone: '',
      email: '',
      password: '',
      passwordConfirmation: ''
    }
  })

  const handleSubmit = (values: SignUpFormData) => {
    onSubmit(values)
  }

  if (signUpSuccess) {
    return (
      <div className='text-center space-y-6'>
        <div className='space-y-2'>
          <h2>{t('users.signup.success_title')}</h2>
          <p>{t('users.signup.success_text')}</p>
        </div>
        <Link
          to={MAP}
          className='inline-block px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors'
        >
          {t('users.signup.back_to_map')}
        </Link>
      </div>
    )
  }

  return (
    <div className='space-y-8'>
      <h2>{t('user.form.sign_up_title')}</h2>
      <div className='max-w-md space-y-8'>
        <p>
          {t('user.form.existing')}{' '}
          <Link to={SIGN_IN}>{t('user.form.sign_in_link')}</Link>
        </p>
        <p className='text-primary/80'>
          mit * markierte Felder werden benötigt
        </p>

        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(handleSubmit)}
            className='space-y-4'
          >
            <FormField
              control={form.control}
              name='name'
              render={({ field, fieldState }) => (
                <FormItem>
                  <FormLabel>{t('user.form.name')} *</FormLabel>
                  <FormControl>
                    <Input type='text' {...field} />
                  </FormControl>
                  <ErrorLabel error={fieldState.error} />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name='phone'
              render={({ field, fieldState }) => (
                <FormItem>
                  <FormLabel>{t('user.form.phone')}</FormLabel>
                  <FormControl>
                    <Input type='text' {...field} />
                  </FormControl>
                  <ErrorLabel error={fieldState.error} />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name='email'
              render={({ field, fieldState }) => (
                <FormItem>
                  <FormLabel>{t('user.form.email')} *</FormLabel>
                  <FormControl>
                    <Input type='email' {...field} />
                  </FormControl>
                  <ErrorLabel error={fieldState.error} />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name='password'
              render={({ field, fieldState }) => (
                <FormItem>
                  <FormLabel>{t('user.form.password')} *</FormLabel>
                  <FormControl>
                    <Input type='password' {...field} />
                  </FormControl>
                  <ErrorLabel error={fieldState.error} />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name='passwordConfirmation'
              render={({ field, fieldState }) => (
                <FormItem>
                  <FormLabel>
                    {t('user.form.password_confirmation')} *
                  </FormLabel>
                  <FormControl>
                    <Input type='password' {...field} />
                  </FormControl>
                  <ErrorLabel error={fieldState.error} />
                </FormItem>
              )}
            />

            <p>
              <span className='block mb-2 text-primary/80'>
                {t('user.form.confirmation')}
              </span>
              <a
                href='https://ernte-teilen.org/nutzungsbedingungen'
                target='_blank'
                rel='noopener noreferrer'
              >
                {t('user.form.terms')}
              </a>
              &nbsp;/&nbsp;
              <a
                href='https://ernte-teilen.org/datenschutz'
                target='_blank'
                rel='noopener noreferrer'
              >
                {t('user.form.privacy')}
              </a>
            </p>

            <Button type='submit' className='w-full' disabled={isLoading}>
              {isLoading ? t('user.form.submitting') : t('user.form.submit')}
            </Button>
          </form>
        </Form>
      </div>
    </div>
  )
}

export default SignUpForm

// packages/map-next/src/routes/users/signup/SignUpForm.svelte
<script lang="ts">
	import * as Field from '$lib/components/ui/field';
	import { Button } from '$lib/components/ui/button';
	import { Heading, Paragraph, FormInput, FormErrorAlert } from '$lib/components/shared';
	import { defaults, superForm } from 'sveltekit-superforms';
	import { zod4, zod4Client } from 'sveltekit-superforms/adapters';
	import * as m from '$lib/paraglide/messages.js';
	import { signUpSchema, type SignUpFormData } from './schema';

	interface Props {
		onSubmit: (values: SignUpFormData) => void;
		signUpSuccess: boolean;
		error?: string | undefined;
		isLoading?: boolean;
	}

	let { onSubmit, isLoading = false, signUpSuccess = false, error }: Props = $props();

	const form = superForm(defaults(zod4(signUpSchema)), {
		validators: zod4Client(signUpSchema),
		SPA: true,
		onUpdate: ({ form }) => {
			if (form.valid) {
				onSubmit(form.data as SignUpFormData);
			}
		}
	});

	const { form: formData, enhance, errors } = form;
</script>

<div class="space-y-8">
	{#if signUpSuccess}
		<Heading level={2}>{m.users_signup_success_title()}</Heading>
		<Paragraph>{m.users_signup_success_text()}</Paragraph>
		<a
			href="#/"
			class="inline-block rounded-md bg-primary px-6 py-2 text-primary-foreground transition-colors hover:bg-primary/90"
		>
			{m.users_signup_back_to_map()}
		</a>
	{:else}
		<Heading level={2}>{m.user_form_sign_up_title()}</Heading>
		<div class="space-y-8">
			<Paragraph>
				{m.user_form_existing()}
				<a href="#/users/signin" class="text-primary underline hover:no-underline">
					{m.user_form_sign_in_link()}
				</a>
			</Paragraph>

			<Paragraph size="small">{m.user_form_required_fields()}</Paragraph>

			<FormErrorAlert {error} />

			<form method="POST" use:enhance class="space-y-4">
				<Field.Group>
					<FormInput
						id="name"
						type="text"
						label="{m.user_form_name()} *"
						bind:value={$formData.name}
						error={$errors.name}
					/>

					<FormInput
						id="phone"
						type="text"
						label={m.user_form_phone()}
						bind:value={$formData.phone}
						error={$errors.phone}
					/>

					<FormInput
						id="email"
						type="email"
						label="{m.user_form_email()} *"
						bind:value={$formData.email}
						error={$errors.email}
					/>

					<FormInput
						id="password"
						type="password"
						label="{m.user_form_password()} *"
						bind:value={$formData.password}
						error={$errors.password}
					/>

					<FormInput
						id="passwordConfirmation"
						type="password"
						label="{m.user_form_password_confirmation()} *"
						bind:value={$formData.passwordConfirmation}
						error={$errors.passwordConfirmation}
					/>
				</Field.Group>

				<Paragraph size="small">
					{m.user_form_confirmation()}
					<a
						href="https://ernte-teilen.org/nutzungsbedingungen"
						target="_blank"
						rel="noopener noreferrer"
						class="text-primary underline hover:no-underline"
					>
						{m.user_form_terms()}
					</a>
					{' / '}
					<a
						href="https://ernte-teilen.org/datenschutz"
						target="_blank"
						rel="noopener noreferrer"
						class="text-primary underline hover:no-underline"
					>
						{m.user_form_privacy()}
					</a>
				</Paragraph>

				<Button type="submit" disabled={isLoading}>
					{isLoading ? m.user_form_submitting() : m.user_form_submit_register()}
				</Button>
			</form>
		</div>
	{/if}
</div>
